name: build vinum

on:
  push:
  pull_request:

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bison \
            flex \
            gcc \
            meson \
            ninja-build

      - name: Configure
        run: meson setup buildir

      - name: Build
        run: meson compile -C buildir

      - name: Run tests
        run: meson test -C buildir --print-errorlogs
